version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - unicart-network

  server:
    image: unicart-server
    container_name: unicart-server
    build: ./server
    ports:
      - "3001:3001"
    restart: always
    environment:
      - DB_CONNECTION=mongodb://mongo:27017/unicart
    networks:
      - unicart-network

  client:
    image: unicart-client
    container_name: unicart-client
    build: ./client
    ports:
      - "80:80"
    restart: always
    links:
      - server
    networks:
      - unicart-network

networks:
  unicart-network:
    driver: bridge
