version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - data1:/data/db
      - config1:/data/configdb
    ports:
      - 27017:27017
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all']
    networks:
      - unicart-network

  server:
    image: unicart-server
    container_name: unicart-server
    build: ./server
    ports:
      - '3001:3001'
    restart: always
    environment:
      - DB_CONNECTION=mongodb://mongo:27017/unicart
      - TOKEN_SECRET=unicartapp
    networks:
      - unicart-network

  client:
    image: unicart-client
    container_name: unicart-client
    build: ./client
    ports:
      - '80:80'
    restart: always
    links:
      - server
    networks:
      - unicart-network

networks:
  unicart-network:
    driver: bridge

volumes:
  data1:
  config1:
